EVENTBRITE_CLIENT_SECRET = 'MNRJ5RQEINNFEDNIYWASLPYNDGOFM7KCJES5JC74S7Y46N3TNA'
EVENTBRITE_CLIENT_ID = 'PZFDCKP3ARMFISBEUW'

LINKEDIN_API_KEY = 'r62cojgm913h'
LINKEDIN_SECRET_KEY = 'tys0ddHMPhmPWTW3'
